FROM fedora:40

COPY entrypoint.sh /entrypoint.sh

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN dnf install -y \
    git \
    cmake \
    boost-devel \
    armadillo-devel \
    gsl-devel \
    blas-devel \
    lapack-devel \
    openssl-devel \
    libcurl-devel \
    libgit2-devel \
    udunits2-devel \
    geos-devel \
    gdal-devel \
    proj-devel \
    sqlite-devel \
    R-core-devel \
    R-devtools \
    R-Rcpp-devel

ENTRYPOINT [ "/entrypoint.sh" ]
